version: '3'
services:

  tsso:
    privileged: true
    hostname: ${TSSO_HOSTNAME}.${DOMAIN}
    build: tsso
    ports:
      - '8048:8048'
    env_file:
      - .env
    stdin_open: true
    tty: true

  tsps:
    privileged: true
    depends_on:
      - tsso
    hostname: ${TSPS_HOSTNAME}.${DOMAIN}
    build: tsps
    ports:
      - '8043:8043'
    env_file:
      - .env
    links:
      - tsso:${TSSO_HOSTNAME}.${DOMAIN}
    stdin_open: true
    tty: true
    command: ['/opt/wait-for-it.sh', 'tsso:8048', '-t', '0', '--', '/opt/install.sh']
    links:
      - tsso:${TSCO_HOSTNAME}.${DOMAIN}

  db:
    hostname: ${DB_HOSTNAME}.${DOMAIN}
    privileged: true
    build: db
    ports:
      - '5432:5432'
    env_file:
      - .env
    environment:
      - POSTGRES_PASSWORD=postgres

  tsco:
    depends_on:
      - db
      - tsps
    env_file:
      - .env
    hostname: ${TSCO_HOSTNAME}.${DOMAIN}
    privileged: true
    build: tsco
    ports:
      - '8443:8443'
      - '8280:8280'
    links:
      - tsso:${TSSO_HOSTNAME}.${DOMAIN}
      - tsps:${TSPS_HOSTNAME}.${DOMAIN}
      - db:${DB_HOSTNAME}.${DOMAIN}
    stdin_open: true
    tty: true
    command: ['/opt/wait-for-it.sh', 'tsps:8043', '-t', '0', '--', '/opt/install.sh']
