CREATE DATABASE "BCO_OWN";   

CREATE ROLE BCO_OWN_ROLE  NOSUPERUSER   INHERIT   CREATEDB NOCREATEROLE NOREPLICATION;
CREATE ROLE BCO_REP_ROLE  NOSUPERUSER NOINHERIT NOCREATEDB NOCREATEROLE NOREPLICATION;

CREATE ROLE "BCO_OWN" LOGIN PASSWORD 'BmcCapac1ty_OWN' SUPERUSER INHERIT NOCREATEDB NOCREATEROLE NOREPLICATION;
GRANT BCO_OWN_ROLE TO "BCO_OWN";
 
CREATE ROLE "BCO_REP" LOGIN PASSWORD 'BmcCapac1ty_REP' NOSUPERUSER INHERIT NOCREATEDB NOCREATEROLE NOREPLICATION;
GRANT BCO_REP_ROLE TO "BCO_REP";
 
ALTER DATABASE "BCO_OWN" OWNER TO BCO_OWN_ROLE;

CREATE TABLESPACE BCO OWNER BCO_OWN_ROLE LOCATION '/data/BCO';
CREATE TABLESPACE BCO_IDX OWNER BCO_OWN_ROLE LOCATION '/data/BCO_IDX';
CREATE TABLESPACE BCO_DATA OWNER BCO_OWN_ROLE LOCATION '/data/BCO_DATA';
CREATE TABLESPACE BCO_DATA_IDX OWNER BCO_OWN_ROLE LOCATION '/data/BCO_DATA_IDX';
ALTER DATABASE "BCO_OWN" SET DEFAULT_TABLESPACE = BCO;


