#!/bin/bash

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" -c "CREATE TABLESPACE BCO OWNER BCO_OWN_ROLE LOCATION '/data/BCO';"
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" -c "CREATE TABLESPACE BCO_IDX OWNER BCO_OWN_ROLE LOCATION '/data/BCO_IDX';"
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" -c "CREATE TABLESPACE BCO_DATA OWNER BCO_OWN_ROLE LOCATION '/data/BCO_DATA';"
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" -c "CREATE TABLESPACE BCO_DATA_IDX OWNER BCO_OWN_ROLE LOCATION '/data/BCO_DATA_IDX';"
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" -c "ALTER DATABASE \"BCO_OWN\" SET DEFAULT_TABLESPACE = BCO;"